# Generated by Django 5.0 on 2023-12-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('download', models.IntegerField(default=0)),
                ('upload', models.IntegerField(default=0)),
                ('period', models.CharField(choices=[('hr', 'hourly'), ('dl', 'daily'), ('wk', 'weekly'), ('mn', 'monthly')], default='mn', max_length=2)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
