# Generated by Django 5.0 on 2023-12-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_address_alter_user_email_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
