# Generated by Django 5.0 on 2023-12-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ip_address',
        ),
    ]
